### ISSUE TITLE
Error - self signed certificate

### ISSUE THREAD

**Issue by kiapkiap** [ImoucheG/sails-sqlserver-v2#5]
Unhandled rejection ConnectionError: Failed to connect to xx.xx.xx.xx:1433 - self signed certificate
    at \icontrolsails\node_modules\mssql\lib\tedious\connection-pool.js:85:17
    at Connection.onConnect (\icontrolsails\node_modules\tedious\lib\connection.js:838:9)
    at Object.onceWrapper (node:events:640:26)
    at Connection.emit (node:events:520:28)
    at Connection.emit (node:domain:475:12)
    at Connection.emit (\icontrolsails\node_modules\tedious\lib\connection.js:959:18)
    at Connection.socketError (\icontrolsails\node_modules\tedious\lib\connection.js:1340:12)
    at \icontrolsails\node_modules\tedious\lib\connection.js:2242:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ImoucheG** [comment]
Hi,

Do you pass `trustServerCertificate` to  `true` ?

` 
options: {
    encrypt: true, // for azure
    trustServerCertificate: false // change to true for local dev / self-signed certs
  }
`

**Comment by kiapkiap** [comment]
yes, i did put in options: { encrypt: true, trustedConnection: true }, but still get the same errr

**Comment by ImoucheG** [comment]
I setup a SQL Server container with self signed certs.
Indeed, i have your error without parameter `trustServerCertificate`

My options are :

```
      options: {
        encrypt: true,
        trustServerCertificate: true, // WARNING The parameter is not trustedConnection like your last message
      },

```

With these options my sailsjs connect to my sqlserver with self signed certs.

**Comment by kiapkiap** [comment]
i found is my mssql version problem, can check which version you using?

**Comment by ImoucheG** [comment]
I use  `mcr.microsoft.com/mssql/server:2019-latest` and `docker pull mcr.microsoft.com/mssql/server:2022-latest`
